[package]
name = "elmdb_nif"
version = "0.1.0"
edition = "2021"

[lib]
name = "elmdb_nif"
crate-type = ["cdylib"]

[dependencies]
rustler = { version = "0.37.0", features = ["nif_version_2_16"] }
lmdb = { git = "https://github.com/permaweb/lmdb-master-rs.git" }
lazy_static = "1.4"